### ISSUE TITLE
Allow specifying custom websocket path

### ISSUE THREAD

**Issue by oakkitten** [glowing-bear/glowing-bear#1008]
Currently, it seems to be [hard-coded](https://github.com/glowing-bear/glowing-bear/blob/84018d4bec3d17cd9edafcd55843054959b9d992/js/connection.js#L30).

**Comment by oakkitten** [comment]
if it was up to me i'd get rid of the port field—typing `:` should be simple enough for weechat users. `foo.org/otherweechat` with a field for a port is a tad uglyish

**Comment by rio-** [comment]
I am running multiple weechat instances on the same machine proxied through nginx. I would love to make all the sockets available on the standard https port using diffferent paths. Right now I have to allocate a bunch of different ports because I can't specify the path in Glowing Bear.

Do you plan on adding this option any time soon?

**Comment by rio-** [comment]
Either you seperate host, port and path into 3 fields or you put them together into one field. Mixing the two is rather unintuitive. I'll see if I can prepare a pull request soon, thanks for answering this quickly!

**Comment by lorenzhs** [comment]
I'd like to avoid changing how it works currently for existing users (not everyone is familiar with the `host:port` syntax, it's easier to separate them), without adding a path field that will confuse everyone except for the four people who will use it. And having the port field autofill if you enter `foo.org:1234` in the host field just makes host a universal field that will autofill the port and the (invisible) path. It's not ideal, and I'm not sure how to document it, but I think it would result in the minimum amount of confusion.
