### ISSUE TITLE
latest.glowing-bear.org is down

### ISSUE THREAD

**Issue by grantwwu** [glowing-bear/glowing-bear#1013]
It appears to not be responding.

**Comment by d0cx** [comment]
...and it seems to be up right now. 👍

**Comment by grantwwu** [comment]
Seems like it's fixed then

**Comment by lorenzhs** [comment]
Sorry about that, I was in a National Park without mobile phone service :) There was a mysterious issue with the server. Quoting from my hoster’s follow up email:

“On 2018-06-08 18:32:10, we noticed a fault on your server and we have scheduled an intervention in order to fix this fault. 

However, on 2018-06-08 18:43:13 our monitoring system did not detect any fault on your dedicated server.

We did not intervene on your machine. We do not know the origin of this fault.

The scheduled intervention has been cancelled from our list.”*

I’ll see if the logs are more helpful than that email once I’m in front of a computer again, but that’s gonna be a while
