### ISSUE TITLE
No encryption tab on the login page

### ISSUE THREAD

**Issue by erikpi** [glowing-bear/glowing-bear#1034]
Hello, after a recent powerloss and restart i found that i can no longer connect to my server with encryption.

I've always gotten the HTTPS error page but being able to bypass the security warning after visiting some link on the login page, that link or tab "encryption" is no longer there.

Attaching an image.  
![image](https://user-images.githubusercontent.com/3598059/47717153-43042780-dc45-11e8-912f-cea721957d4b.png)

**Comment by lorenzhs** [comment]
Yes, that's intentional. You can still go to `https://host:port/weechat` (e.g. `https://192.168.0.123:9001`) manually, but you should really use a certificate that's trusted by your browser. Blindly accepting the certificate every time is better than no encryption, but worse than a trusted certificate (because a man in the middle could intercept your connection and pretend to be your server).

It really is very simple to get a certificate with Let's Encrypt.
