### ISSUE TITLE
Push notification for every message

### ISSUE THREAD

**Issue by piegamesde** [glowing-bear/glowing-bear#1044]
Currently I only get desktop notifications when I'm highlighted. I'd like to have the option to get one for every message in certain channels.

This feature request is quite the opposite of #1031 so there should be an option to toggle this somewhere.

**Comment by lorenzhs** [comment]
Notifications are determined by weechat notify levels, so if you want to be notified, you need to configure weechat to notify you for every message. We don't support independent notification settings at the moment (mostly because doing what weechat does is a good default for 95% of use cases, and it would be a lot of work).

**Comment by piegamesde** [comment]
I got it working how I'd like to by executing `/buffer set highlight_regex .*` as told in [the documentation](https://weechat.org/files/doc/devel/weechat_user.en.html#highlights_regex_buffer)
