### ISSUE TITLE
Notification sound volume settings

### ISSUE THREAD

**Issue by piegamesde** [glowing-bear/glowing-bear#1161]
It's hurting my ears. Telegram does this for example:

![image](https://user-images.githubusercontent.com/14054505/95775438-b7192800-0cc2-11eb-91b7-8645c4df0f46.png)

**Comment by lorenzhs** [comment]
I'm not sure I understand the problem. I assume you're on a desktop/laptop? Can't you just use the operating system's volume settings? Windows and Linux (pulseaudio) let you set the volume for each application separately, I'm not sure about macOS.

**Comment by piegamesde** [comment]
Setting the volume per application is not enough. There are browser extensions that allow per-tab volume settings, but I think that until this is a common thing (both Chrome and Firefox provide this as built-in feature) applications should rather provide their own slider.

**Comment by lorenzhs** [comment]
Well why don't you just use one of those extensions then? In the >5 years that I've been involved with Glowing Bear I've never seen a request for this feature from anyone else (neither here nor on IRC), and I'm a strong proponent of keeping the settings page as simple as possible. Since a good workaround exists, I'm going to close this.
