### ISSUE TITLE
Unable to connect with HTTPS address, but port 443 works fine

### ISSUE THREAD

**Issue by Linkandzelda** [glowing-bear/glowing-bear#1192]
A little oddity I discovered today when trying to connect to my relay. Entering https://relay will give an error about the browser not being able to trust the certificate. Or specifically "Secure connection error A secure connection with the WeeChat relay could not be initiated.".

Taking out the https:// part of the address and putting port 443 directly allows me to connect without problems.

**Comment by u1f408** [comment]
Entering a full URL in the "host" field is not supported, as per the "Setting a custom path" section of the "Usage instructions" section on the Glowing Bear connection page. Even if it was supported, you wouldn't be able to use `https://`, it would have to be `wss://` (because the connection to weechat uses a WebSocket).

**Comment by Linkandzelda** [comment]
Thanks for the insight. What lead me to believe it was supported is that when entering a path starting with https:// or wss:// the port field is greyed out. The application behaves in such a way that it seems it knows what I want. If it's not intended to work then how come this happens?

**Comment by u1f408** [comment]
> when entering a path starting with https:// or wss:// the port field is greyed out

@Linkandzelda If I'm remembering correctly - it's been a while since I've looked at that part of the code - this is because Glowing Bear sees a `/` and assumes that everything from the `/` onwards is a relay WebSocket path (to use instead of `/weechat`), it's not trying to parse that as a protocol + host/port + path. In this case it's very likely that it's trying to use `https` as a host name, and `/relay` as the path.

The pull request that has been linked here a couple days ago by @​lorenzhs will fix this - once that's merged, Glowing Bear will behave how you expect it to in this case.
