### ISSUE TITLE
Icons showing as unrelated emoji

### ISSUE THREAD

**Issue by Minnozz** [glowing-bear/glowing-bear#1204]
On latest.glowing-bear.org, on iOS

![image](https://user-images.githubusercontent.com/701386/150691617-9b82611e-5242-4ea7-b8d3-2f3bf53f82e2.jpeg)

**Comment by gothicserpent** [comment]
![2022-01-23 17_30_55-Glowing Bear #linux _ Welcome to #linux! Help_support for any Linux distribution](https://user-images.githubusercontent.com/36061843/150708235-a9788d85-5ecc-4976-8b67-8a540b7235c3.jpg)

same here, i believe it's related for me too. on the top right in my windows chrome panel, there are to boxes instead of the standard gear and power icons. 

this just started happening today or yesterday i believe along with the most recent commit 6508993fea5e4bd2a00f5809433ca9e2c914881a

**Comment by lorenzhs** [comment]
Thanks for the report! I'm mostly a "click merge" kind of maintainer these days - I don't have time to maintain GB properly any more so it'd be very helpful if you were able to figure out whether #1186 (https://github.com/glowing-bear/glowing-bear/commit/6508993fea5e4bd2a00f5809433ca9e2c914881a) or https://github.com/glowing-bear/glowing-bear/commit/11d53f103f44766242e250948b80a176c0118ded caused this and how we might be able to fix it

**Comment by Minnozz** [comment]
The problem is that the glyphicons dependency via `twitter-bootstrap` no longer loads:
<img width="1397" alt="Screenshot 2022-02-01 at 21 33 45" src="https://user-images.githubusercontent.com/701386/152046740-2380af42-314c-43e6-979d-c6a7998bac2d.png">
It is mentioned here: https://github.com/glowing-bear/glowing-bear/pull/1186/files#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR42-R43

The problem seems to be that it is copied to the `css` subdirectory instead of the `fonts` subdirectory. I will submit a fix.
