### ISSUE TITLE
Unread counter is in an unfortunate place if the buffer name is long

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#319]

**Comment by omnicons** [comment]
I mean personally I removed the css you all were using so that it shifts my IRC channels to the right when an unread counter came up so that it gave more prominent attention and also didn't make it look ugly in the process by simply hiding part of the longer channel names.
.pull-right {
float: left!important
}

**Comment by lorenzhs** [comment]
This has been fixed for a while
