### ISSUE TITLE
Consider making app fully self hostable?

### ISSUE THREAD

**Issue by adamcik** [glowing-bear/glowing-bear#436]
For the paranoid souls among us it would be nice if we could have an option to not rely on any external CDNs.

**Comment by comex** [comment]
I was going to file a similar issue before finding this one.  I am fairly paranoid, and like to use a setup that mitigates hypothetical attacks by well-funded attackers, even if I don't think I'm actually likely to be targeted by such attackers.  Accordingly, I run Glowing Bear on localhost, so that compromise is only a potential problem when I update it, as opposed to running from a server which could at any time start sending different scripts to specific hosts, etc.

Even though it's not hard to do this manually, it would be nice if it were available by default somehow, e.g. by including the files in the repository and including some code to use them by default if running from localhost.  (Or something using Bower?  I don't know how that works but saw it in the repository.)

**Comment by lorenzhs** [comment]
@comex just cherrypick this commit onto master: https://github.com/glowing-bear/glowing-bear/commit/7ad30a1e70b9399f7b632c501216c268bfeef2d8

You can then update the dependencies by running `bower install` (or update? I forgot) and `cp bower-foo/**/*.min.* 3rdparty` (forgot the exact name of the directory, but you know what I mean)

You see, it's not hard!

Btw, I'm not sure if I remembered for all of them, but I usually try to think of signing tags when pushing a new release. Added protection from interference ;)
