### ISSUE TITLE
Switch buffers with Alt+arrow

### ISSUE THREAD

**Issue by blasphemy** [glowing-bear/glowing-bear#511]
I use this extensively on the CLI client, but it doesn't work in glowing bear. Is this possible to implement?

**Comment by Maffblaster** [comment]
I'd like this feature as well if possible. Since the channels are currently displayed in a vertical manner it might be best to use the ↑ and ↓ keys (up and down).

If there are other hot keys available in GB it would be nice to have a legend for available hotkeys. I currently do not know how to view if any hot keys are available.

**Comment by rickybrent** [comment]
I did a fork of GB with alt-up and alt-down. That works great on my linux PC but not on my chromebook. :) 

It's a bit more complicated than it seems since the visual order shown by glowing bear isn't always the same as the actual order by index; since I was just coding it for me I didn't care too much but if I was going to clean it up and make a pull request that'd be important.

**Comment by Maffblaster** [comment]
It would be nice to not have to leave the keyboard when connecting via the web interface, although search can be done with an Alt+g, I still think this feature would be used. :+1:

**Comment by 20after4** [comment]
:heart: This is the biggest WTF in glowing-bear. It's sad that this hasn't been implemented but I looked into it and it turned out to be a lot messier and more difficult than I expected.

**Comment by lorenzhs** [comment]
Fixed with #691
