### ISSUE TITLE
Firefox-based App + Self-signed SSL == :-(

### ISSUE THREAD

**Issue by djbclark** [glowing-bear/glowing-bear#544]
It's really non-obvious how to use the Firefox-based app (Install app -> big blue "Install Firefox app" button). How to do it should be doc'ed and linked to next to the app install button.

Specifically the app doesn't share state with the installed firefox, so you can't just accept the self-signed ssl cert there. And you can't open a normal browser window from within the app from which to accept the cert. So you have to do the following:

(a) In firefox, go to https://machinename:port where machinename and port correspond to the box you have weechat on. No web page will come up, but you should be prompted to accept the self-signed certificate.

(b) Close firefox and glowing bear

(c) Find the firefox profile for the normal firefox in which you accepted the self-signed certificate, and the profile for the glowing bear app. These may be in completly different directory trees. To find this I just searched for a file that's always in profiles; at the time, the "urlclassifierkey3.txt" file fit the bill.

(d) Copy the "cert_override.txt" file from your normal profile to the glowing bear profile. Haven't tested this, but I'm guessing a symbolic link would also work, and have the advantage of easy updates if the machine you have weechat running on changes.

**Comment by lorenzhs** [comment]
Hi

**Comment by lorenzhs** [comment]
Hi! There should be a link in the encryption instructions that will take you to https://machinename:port, and you should be able to accept the certificate right from the firefox app. I don't use Firefox so I haven't tested it, can you tell me whether that works?

Otherwise, what you describe are mostly Firefox issues, but you're right in that we should do a better job of explaining the consequences of using GB as a firefox app.

We should also add a link to the Play Store / Firefox OS Marketplace under "install app"...

Lastly, it's quite easy to get a trusted certificate for your relay (which will solve many of your issues); I made a post about that at https://4z2.de/2014/07/06/weechat-trusted-relay
