### ISSUE TITLE
Add horizontal bar separating old from new messages when switching to a buffer.

### ISSUE THREAD

**Issue by bj0** [glowing-bear/glowing-bear#629]
One of the most useful things in weechat is the hbar that appears above unread messages when you switch to a buffer.  It lets your eye instantly find the first new message.  

I see there is an hbar that starts at the bottom when you switch to a channel. It would be more useful, in my opinion if it was placed above unread messages when switching to a buffer containing them.

*EDIT:* 
So I just saw this happen with one of my buffers (with 2 new messages), so I am guessing this is how it is supposed to work.  All other times I've switched, the bar goes to the bottom, so I guess this is a bug.

**Comment by lorenzhs** [comment]
Hi @bj0, thanks for your report. As you've mentioned in your edit, the readmarker is supposed to do exactly that. Can you provide more detail about the buffers this happened to? (how many unread messages did they contain, and how many lines were shown when you switched there?)

For me, the read marker is at the bottom only if the buffer I'm switching to has no unread lines. Otherwise, it is either at the correct position (all unread lines shown) or not shown (all lines shown are unread, but there are more unread lines that haven't been loaded).

**Comment by bj0** [comment]
I'll try and pay more attention to what the numbers on the buffers are.  I'm using https://latest.glowing-bear.org/#, in Firefox (38), on Ubuntu 15.04.

I just switched to #octoprint, which had 300+ unread messages and the readmarker was at the bottom.  
I just switched to #kivy, which had less. 

What I just noticed is that sometimes switching buffers takes a while, so I will click on it a second time, and this may be resetting the readmarker.

**Comment by lorenzhs** [comment]
Yup, that's it. When you first click, the read status is updated in WeeChat, so when you click a second time, WeeChat and Glowing Bear think you've already read everything.

Buffer switching really is a bit slow if it has to show many lines. That's a problem with how the DOM elements are created and we already have an issue about that at #87. I'm closing this one then.
