### ISSUE TITLE
Display a single "view media" button for duplicated media links

### ISSUE THREAD

**Issue by Zopieux** [glowing-bear/glowing-bear#636]
On some occasions, eg. when changing the `/topic`, a media URL (typically an image) will appear twice in the same IRC line. At the moment Glowing Bear displays two "View <thing>" buttons that do the same thing, which is not nice. It would be great to add some dedup feature so that only one button is displayed.

**Comment by lorenzhs** [comment]
Hmm it should be possible to do this for most plugins at once by adding deduplication here: https://github.com/glowing-bear/glowing-bear/blob/d07ba4edd1bde923152f203be7e346a08a083a3e/js/plugins.js#L36

Not sure how to do this most efficiently, since the expected list length is very short and we need to preserve ordering.

**Comment by lorenzhs** [comment]
After only one and a half years I've come around to adding a call to `_.uniq` to UrlPlugin... #854 fixes this. That was easy. Sorry it took so long.
