### ISSUE TITLE
Bufferlist strangely organized when >1 account for 1 network.

### ISSUE THREAD

**Issue by emdantrim** [glowing-bear/glowing-bear#662]
I connect to one IRC network with two different accounts (work/personal), and all channel buffers for each account are filed in the same section as one another, rather than each being underneath their own respective server buffer, like you find with other servers.

For example, where the expected behavior would be:
- `server 1`
- `channel 1 1`
- `channel 1 2`
- `server 2`
- `channel 2 1`
- `channel 2 2`

I get
- `server 1`
- `server 2`
- `channel 1 1`
- `channel 1 2`
- `channel 2 1`
- `channel 2 2`

**Comment by lorenzhs** [comment]
@emdantrim can you retry this on https://latest.glowing-bear.org/? We recently made the logic that controls buffer ordering a lot cleaner, maybe this got fixed in the process.

**Comment by emdantrim** [comment]
@lorenzhs nope, it still is organized the same way on `latest`. :(

**Comment by lorenzhs** [comment]
Dang, I was hoping we could get out of this cheaply. It's just ordered by the buffer's full name, with a bit of special treatment for server buffers. To fix this, we'd have to order it by plugin (irc) then network then account and *then* buffername (e.g. `irc.freenode.fooacc.#glowing-bear` instead of `irc.freenode.#glowing-bear`).

Maybe there's another way to do it?
