### ISSUE TITLE
DNS Pre-fetch information leak

### ISSUE THREAD

**Issue by KimBrodowski** [glowing-bear/glowing-bear#674]
In certain scenarios the DNS pre-fetch feature of modern browsers can leak whether a user has read a message or not when using Glowing Bear. Also it will reveal the client's actual IP-address when using Glowing Bear to access a remote WeeChat relay while running a local dedicated DNS resolver. Disableing dns-prefetching should solve that.

`<meta http-equiv="x-dns-prefetch-control" content="off">`

**Comment by lorenzhs** [comment]
Hm, I don't think the information leak is particularly serious as it's quite hard to exploit (basically I need to run your DNS server or observe your DNS traffic). On the other hand, the gains from DNS prefetching are really quite low (on a low-latency connection, modern web pages take ages to load anyway because of all the JS frameworks, analytics which bundle the same frameworks once again, ads, etc - one additional round trip really doesn't matter there. However, DNS prefetching may actually be useful on slow mobile connections). All in all, I don't have a strong opinion either way.

**Comment by KimBrodowski** [comment]
You don't need to run "my" DNS-server. It's enough to run your own nameserver. Create your own authoritative nameserver for the zone dnsspy.example.com. Setup the NS to log all queries to that zone. Send a random person a message containing the link http://uniquemessageid123.dnsspy.example.com (They need to use a vulnerable client, like Glowing Bear, though) . Watch the logfile. Once the person opens the buffer containing the message you should have an incoming query. The IP shown in the logfile is the IP of the DNS resolver the client is using (allowing you to get an idea where the client is located and which ISP he's using), unless the user runs his own resolver.  In that case the client's IP is "leaked".

**Comment by lorenzhs** [comment]
Hm, right, I missed that. It might be a good idea to fix this then.
