### ISSUE TITLE
No show button in certain cases

### ISSUE THREAD

**Issue by TimelessBeing** [glowing-bear/glowing-bear#736]
I'm not exactly sure if it's a bug of a feature, but when I post the URL of an image there are two possible behaviours:
-  if the URL starts by "http://": it is identified as an URL, converted into a link, and gives access to a "Show" button
- if the URL starts by "www.": it is also identified as an URL and converted into a link, but does not give access to a "Show" button

**Comment by lorenzhs** [comment]
Yeah, that's because we use angular's `linky` for linkification but have to detect image links ourselves. The code that does that detection requires a protocol specifier (`http://` or `https://`) because that's a lot easier to identify than go around guessing what might be a URL. It's easy for people but not as simple for machines ;)

**Comment by TimelessBeing** [comment]
Can't you simply detect the <a></a> tags after linky did its work to identify URLs?
(I didn't look into the code to see how things are implemented, so I'm not sure how possible that is)

**Comment by lorenzhs** [comment]
Nope, the filters (link etc) are run after the plugins (the things with show buttons). You're welcome to improve the url regex though, have a look at `js/plugins.js` if you're interested

**Comment by lorenzhs** [comment]
Closed with #737
