### ISSUE TITLE
"Hierarchical buffer view (order by server)" changes buffer order within server

### ISSUE THREAD

**Issue by DBendit** [glowing-bear/glowing-bear#777]
When the "Hierarchical buffer view (order by server)" option is enabled, buffers are sorted alphabetically within the containing server. I would expect the relative buffer order to remain unchanged within each server.

Would it be possible to either add an option or to change the default functionality such that, in hierarchical buffer view, the relative buffer order is maintained within each server?

**Comment by lorenzhs** [comment]
That's intended behaviour.

Changing the meaning of a setting is never a good idea. It's a great way to upset lots of people, though.

We're also trying to keep the number of options to a minimum. Given that this is a very niche feature (nobody has ever brought it up before, if memory serves me), I think that it would be unlikely to land in the main repo. Fortunately, it's both really easy to change this behaviour (just set the `serverSortKey` variable in [js/buffers.js](js/buffers.js) so that it sorts in the way you want to) and to use a fork (do your changes in the `gh-pages` branch and github will host your fork for you, you can use it at https://<username>.github.io/glowing-bear).

**Comment by lorenzhs** [comment]
Oh, btw, to make this change just replace `shortName` with `number` in https://github.com/glowing-bear/glowing-bear/blob/5e1dfbf8f011b4591d78d6b95adaff6bd8ecf4d0/js/models.js#L100 - should work
