### ISSUE TITLE
Hide given set of "secondary" buffers

### ISSUE THREAD

**Issue by JulienPalard** [glowing-bear/glowing-bear#891]
I'd like the possibility to permanently hide a buffer, client side *on a single client* (allowing me to hide *a different set of channels* on *different glowing bear client* connected to the same weechat server).

Idea is: I'm on some channels that I don't really follow (lets name them secondary channels), if I read them, I do only occasionally on my desktop cilent, those channels are making my mobile client hard to use because I have hard times to find my "primary channels" on it between the secondary ones.

I can't /leave those secondary channels due to the well known "I may miss something important" effect, but I also don't want them to lower the usability of my mobile client þ

**Comment by lorenzhs** [comment]
Hi Julien! That's a fairly specific use case :) I think the way to implement this with the least amount of effort (but not a very convenient UI) would be to add a buffer's fullname to its bufferlist entry as a class, and then hide those buffers using custom CSS. Maybe you can even filter by its `<a>` child whose title attribute is the fullname.

Since implementing this properly with client-side storage would be quite a bit of work, I don't think doing this is something we're interested in right now, sorry. If you can make the workaround work, that would probably be easiest. I hope you understand!

**Comment by JulienPalard** [comment]
> Hi Julien! That's a fairly specific use case :)

Yup!

> I think the way to implement this with the least amount of effort (but not a very convenient UI) would be to add a buffer's fullname to its bufferlist entry as a class, and then hide those buffers using custom CSS. Maybe you can even filter by its <a> child whose title attribute is the fullname.

Probably, but on Android… I won't do it þ.

> Since implementing this properly with client-side storage would be quite a bit of work, I don't think doing this is something we're interested in right now, sorry.

Legitimate, and I understand. At least if a ton of people is interested, they'll +1 this issue and we'll know. While I'm alone needing it, I understand you won't do it. Also if I really need it I can do it myself, but I did not even started to read your code þ
