### ISSUE TITLE
Imgur embeds break in Electron app.

### ISSUE THREAD

**Issue by ttheuer** [glowing-bear/glowing-bear#913]
Leaving the protocol part empty (`url = url.replace(/http:/, "");`) does not seem to work in Electron. (Tbf, I don't know why it works *anywhere*).

**Comment by txanatan** [comment]
As far as I understand, it works in the browser because just using "//" uses the current protocol - so it'll use HTTPS if Glowing Bear is loaded over HTTPS, HTTP if GB is loaded over HTTP, etc. This will break in Electron because it uses "file://" addresses, therefore attempting to load "file://i.imgur.com/filename.jpg".

**Comment by Techman-** [comment]
This is probably the best approach because it's good practice to use HTTPS at this point anyways. I wonder if similar modifications could be done for the other embedded items if their host offers HTTPS explicitly.
