### ISSUE TITLE
Upload images to own server

### ISSUE THREAD

**Issue by mcnesium** [glowing-bear/glowing-bear#925]
Uploading images directly to Imgur can be convenient in some cases, but if not logged in with an Imgur account, I'm never going to be able to delete the uploaded image again. Also, when running Glowing Bear on my own server, it would make sense to also upload images to it as well.

Instead of just forking and start hacking I would like to discuss what would need to be done, to obey upstream conventions and further eventual constraints.

Maybe someone already started to work on this.

**Comment by lorenzhs** [comment]
It doesn't link them to your imgur account anyways, so you won't be able to delete them no matter what ;)

Uploading images to your own server would require some server-side component (something that accepts images, stores them somewhere, and gives you the link). Since Glowing Bear is pure client-side javascript, we can't do this without giving up most of our design principles. If you have some software that mimics the imgur API, then we could think about making the image host configurable. But otherwise this is way beyond our scope.

**Comment by quite** [comment]
I think supporting this would be great, and if you ask me it goes hand in and with "hosting" your own IRC-client, here a relaying Weechat. This is how an Android app for the Weechat-relay does it: https://github.com/ubergeek42/weechat-android/wiki/File-sharing

**Comment by Mikaela** [comment]
How about Nextcloud? That is what Palaver supports as an alternative to Imgur. I don't know what it involves, but I dug this link from another project discussing it

* https://justyn.io/til/upload-files-to-nextcloud-using-curl-and-webdav/

**Comment by lorenzhs** [comment]
I would be fine with merging a PR that implements uploading to a reasonable self-hosted alternative, but someone (not me) will have to implement it

**Comment by oakkitten** [comment]
why not make it configurable?
