### ISSUE TITLE
Embeds: Videos, etc. are not automatically paused when collapsed

### ISSUE THREAD

**Issue by Techman** [glowing-bear/glowing-bear#975]
This is a small issue in the grand scheme of thing, but it would be a nice quality of life improvement.

The current behavior is that items such as YouTube videos and Streamable embeds will continue to play even when their button is toggled to close. It would be nice if they paused before collapsing.

**Comment by AStove** [comment]
Due to iframes this is impossible. You cannot access elements inside the iframe with javascript due to cross-origin poicies. So pausing the video is impossible. Unless you specifically use the youtube api and such.

What does work is unloading the iframe, but then has to be reloaded when you open it again. To me this seems fair enough because who would want to pause it, then reopen it to continue watching..
